### ISSUE TITLE
I think it is not necessary to give a vm that is set to not  unmigratable a solution.

### ISSUE THREAD

**Issue by yingyun001** [oVirt/ovirt-optimizer#1]
I view that if a vm that is unable to migration, it doesn't need to a solution. Or maybe optaplanner have another strategy that give a solution that is not about migration. Just a little advice. Thank you. ：）

**Comment by david-caro** [comment]
Hi, this issue tracker is not active, if this is still an issue please open a bug in http://bugzilla.redhat.com (ovirt-optimizer product). Thanks
